version: "3.7"
services:
  web:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dockerfile
    depends_on:
      - app
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8880:80"
      - "443:443"
    links:
      - app
    restart: always
  app:
    container_name: php
    image: php:fpm
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./html:/var/www/html
    environment:
      PMA_HOST: db
      PMA_USERE: test
      PMA_PASSWORD: root
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8888:80"
    depends_on:
      - db
